In [1]:
import numpy as np
import pandas as pd

**Pivot Tables**

In [12]:
data = {
    'Date':pd.date_range('2023-02-02', periods=20),
    'Product':['A','B','C','D'] * 5,
    'Region':['East', "West", 'North','South','East','West','North','South','East','West',
              'North','South','East','West','North','South','East','West','North','South'],
    'Sales':np.random.randint(100, 1000,20),
    'Units': np.random.randint(10, 100, 20),
    'Rep':['John','Harry','Bob','Alice','John','Mary','Alice','John','Mary','Bob',
           'Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice','Bob']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep     Month Quarter
0  2023-02-02       A   East    829     41   John  February      Q1
1  2023-02-03       B   West    158     80  Harry  February      Q1
2  2023-02-04       C  North    328     99    Bob  February      Q1
3  2023-02-05       D  South    417     80  Alice  February      Q1
4  2023-02-06       A   East    859     94   John  February      Q1
5  2023-02-07       B   West    487     77   Mary  February      Q1
6  2023-02-08       C  North    451     71  Alice  February      Q1
7  2023-02-09       D  South    456     97   John  February      Q1
8  2023-02-10       A   East    806     53   Mary  February      Q1
9  2023-02-11       B   West    459     63    Bob  February      Q1
10 2023-02-12       C  North    588     69  Alice  February      Q1
11 2023-02-13       D  South    417     80   John  February      Q1
12 2023-02-14       A   East    541     78   Mary  February      Q1
13 2023-02-15       B   West    232     84    Bob  February      Q1
14 2023-02-16       C  North    708     96  Alice  February      Q1
15 2023-02-17       D  South    393     54   John  February      Q1
16 2023-02-18       A   East    962     43   Mary  February      Q1
17 2023-02-19       B   West    513     41    Bob  February      Q1
18 2023-02-20       C  North    642     39  Alice  February      Q1
19 2023-02-21       D  South    538     41    Bob  February      Q1

In [14]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product')

Product      A      B      C      D
Region
East     799.4    NaN    NaN    NaN
North      NaN    NaN  543.4    NaN
South      NaN    NaN    NaN  444.2
West       NaN  369.8    NaN    NaN

In [15]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product', aggfunc='median')

Product      A      B      C      D
Region
East     829.0    NaN    NaN    NaN
North      NaN    NaN  588.0    NaN
South      NaN    NaN    NaN  417.0
West       NaN  459.0    NaN    NaN

In [17]:
pivot2 = pd.pivot_table(df,values=['Sales','Units'],index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     799.4    NaN    NaN    NaN  61.8   NaN   NaN   NaN
North      NaN    NaN  543.4    NaN   NaN   NaN  74.8   NaN
South      NaN    NaN    NaN  444.2   NaN   NaN   NaN  70.4
West       NaN  369.8    NaN    NaN   NaN  69.0   NaN   NaN

In [19]:
# pivot3 = pd.pivot_table(df,values=['Quarter','Units'],index='Region', columns='Product')
# pivot3  # value must be numeric not Like (Quarter)

**Cross Tabs**

In [22]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0